# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Creating Sandvine SVMCDTEXT Repository - Production
  template: src=Sandvine-SVMCDTEXT.repo
            dest=/etc/yum.repos.d/Sandvine-SVMCDTEXT.repo
            owner=root
            group=root
            mode=0644
  when: release == 'prod'

- name: Creating Sandvine SVMCDTEXT Repository - Development
  template: src=Sandvine-SVMCDTEXT_dev.repo
            dest=/etc/yum.repos.d/Sandvine-SVMCDTEXT.repo
            owner=root
            group=root
            mode=0644
  when: release == 'dev'


- name: Installing required SVMCDTEXT packages
  yum: pkg={{item}} state=latest state=latest
  with_items:
    - perl-XML-Simple
    - svmcdtext
