# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: centos6 - service disabling iptables firewall
  service: name=iptables state=stopped enabled=no


- name: centos6 - copy SSH Daemon config - RootLogin & PassAuth enabled!
  copy: src=centos6/sshd_config
        dest=/etc/ssh/sshd_config
        owner=root
        group=root
        mode=0600
        backup=yes


- name: centos6 - yum installing required packages for "labify-linux.sh"
  yum: pkg={{item}} state=latest
  with_items:
    - nfs-utils 


- name: centos6 - service enabling NFS
  service: name={{item}} enabled=yes
  with_items:
    - rpcbind
    - rpcidmapd
    - nfslock
    - netfs


- name: centos6 - copy Labify 2
  copy: src=centos6/fetchlabify
        dest=/etc/init.d/fetchlabify
        owner=root
        group=root
        mode=0755


- name: centos6 - service enabling fetchlabify
  file: src=/etc/init.d/fetchlabify
        dest=/etc/rc3.d/S90fetchlabify
        state=link
        force=yes
