# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# New style URLs - upgradeable
- name: centos | copy Sandvine SVPTS Repository - Production
  template: src=common/Sandvine-SVPTS.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: release == 'prod'


- name: centos | copy Sandvine SVPTS Repository - Development
  template: src=common/Sandvine-SVPTS_dev.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: release == 'dev' and static_repo != 'true'


- name: centos | copy Sandvine SVPTS Repository - Development - Versioned
  template: src=common/Sandvine-SVPTS_versioned.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: versioned_repo == 'true' and release == 'dev' and static_repo != 'true'


# Old style URLs - non-upgradeable
- name: centos7 | copy Sandvine SVPTS Repository - Static - Production
  template: src=centos7/Sandvine-SVPTS_static_versioned.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: base_os == 'centos72' and static_repo == 'true' and versioned_repo == 'true' and release == 'prod'


- name: centos7 | copy Sandvine SVPTS Repository - Static - Versioned
  template: src=centos7/Sandvine-SVPTS_static_versioned_dev.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: base_os == 'centos72' and static_repo == 'true' and versioned_repo == 'true' and release == 'dev'


- name: centos6 | copy Sandvine SVPTS Repository - Static - Versioned
  template: src=centos6/Sandvine-SVPTS_static_versioned_dev.repo
            dest=/etc/yum.repos.d/Sandvine-SVPTS.repo
            owner=root
            group=root
            mode=0644
  when: base_os == 'centos67' and static_repo == 'true' and versioned_repo == 'true' and release == 'dev'


# Deployment
- name: centos | yum installing the Linux SVPTS
  yum: pkg={{item}} state=latest
  with_items:
    - svpts


- name: centos | copy Sandvine SVPTS login logo
  copy: src=etc-issue-pts-logo
        dest=/etc/issue
        owner=root
        group=root
        mode=0644


- name: centos | yum excluding the kernel out from upgrades (DPDK issue)
  lineinfile: dest=/etc/yum.conf line="exclude=kernel"
