# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: SDE workaround, "/etc/init.d/sde" sudo reset_permissions requirement
  lineinfile: dest=/etc/sudoers
              insertafter='^Defaults.*requiretty'
              line='Defaults:root !requiretty'
              validate='visudo -cf %s'


- name: Creating Sandvine SDE Repository - Production
  template: src=common/Sandvine-SDE.repo
            dest=/etc/yum.repos.d/Sandvine-SDE.repo
            owner=root
            group=root
            mode=0644
  when: release == 'prod'


- name: Creating Sandvine SDE Repository - Development
  template: src=common/Sandvine-SDE_dev.repo
            dest=/etc/yum.repos.d/Sandvine-SDE.repo
            owner=root
            group=root
            mode=0644
  when: release == 'dev'


- name: Creating Sandvine SDE Repository - Development - Versioned
  template: src=common/Sandvine-SDE_versioned.repo
            dest=/etc/yum.repos.d/Sandvine-SDE.repo
            owner=root
            group=root
            mode=0644
  when: sde_versioned == 'true' and release == 'dev'

 
- name: Installing required packages and the SDE
  yum: pkg={{item}} state=installed
  with_items:
    - sde
    - perl-libs
    - perl-XML-Parser
    - perl-XML-Simple
    - perl-libwww-perl


- name: Managing Local Firewall Rules
  command: "{{item}}"
  with_items:
  - lokkit --port=22:tcp --update
  - lokkit -t eth1
  - service iptables save
  when: is_container != 'yes'
